### ISSUE TITLE
How to determine ratelimit reset

### ISSUE THREAD

**Issue by brussell98** [AniList/ApiV2-GraphQL-Docs#20]
I'm currently working on migrating to the new API, but I'm having trouble determining how to handle ratelimiting.

From the docs, a `x-ratelimit-reset` header is only provided when you go over the ratelimit, which isn't very helpful in avoiding that. I did some testing and noticed that it resets at different times. Once at ~13 seconds and once ~38 seconds, so syncing with 00 seconds won't work either. If I could have a more sure way, such as always having the header, it would help me avoid accidentally going over the limit or having to pause for arbitrary amounts of time.

**Comment by joshstar** [comment]
The minute timeout starts at the second of the first out of limits request made, so if that request is made at 33 seconds past the minute, the timeout will expire 33 seconds into the next the minute. 

The `X-RateLimit-Remaining` header is always returned and provides the amount of remaining requests you can make in the current rate-limit period, so going off that should help with avoiding going over the limit.

If you need it there is the option to raise the rate limit for a specific IP, more info on that at the bottom of [this page](https://anilist.gitbooks.io/anilist-apiv2-docs/rate-limiting.html)

**Comment by brussell98** [comment]
Sorry if I wasn't clear, but I meant the reset time for remaining requests (before hitting 0). Currently I just start a 60 second reset timer on the first request, but since that isn't in sync with the server's timer it can easily go over. When the remaining requests hits 0 I have no way of knowing when I can make requests again. This creates a problem when users expect an immediate response and I have to delay it unnecessarily long.

**Comment by joshstar** [comment]
Ah okay sorry I understand what you mean now. At what time does the rate-limit period end, so you can make sure to not go over the limit before that and just wait out the remaining time instead of waiting the for timeout minute to end.

I've added the `x-ratelimit-reset` header to all responses and that will have the timestamp of when the rate-limit period ends and your request limit count resets.

Currently we do have a bit of an issue where our cache drivers time is a little out of sync with real time, so technically the rate limit may be reset a couple seconds early but I'll be getting that fixed within the next couple days.
