### ISSUE TITLE
Media Social Tab w/ API?

### ISSUE THREAD

**Issue by markphilpot** [AniList/ApiV2-GraphQL-Docs#28]
I've been trying to figure out how I might generate a media's social tab (e.g. https://anilist.co/anime/99426/SorayorimoTooiBasho/social) using the api and I can't figure out a way to do it without brute forcing (for each user the viewer is following run `MediaList(userId, mediaId)`)

Is there method I might have missed that would be something like a media list response for a given mediaId across a set of users?  Something like `MediaSocial(mediaId: Int, userId_in: Int[])`

**Comment by joshstar** [comment]
Sorry for the late reply.

I've added an `isFollowing` argument which will limit the query to the users the currently authd user is following, so that should allow for the same data set as on the social page.  Also added `userId_in` just in case you want to manually specify those users too.

Will push these changes within the next couple hours.
