### ISSUE TITLE
Feature: Add a "media title" sort option to MediaListSort

### ISSUE THREAD

**Issue by markphilpot** [AniList/ApiV2-GraphQL-Docs#34]
It would be great to be able to sort a media list alphabetically by the media title. Not sure it's possible given the variations of media title and that `userPreferred` is probably dynamic. Maybe could just have a separate MediaListSort option for each of the possible title variations?

**Comment by joshstar** [comment]
Due to the way media is joined onto the media list db query this isn't really possible currently, depending on the complexity of the query our orm will sometimes use eager loading instead of a left join. We also have a system, to automatically transform graphql queries into orm queries and adding an exception just for this case might be a bit of a challenge. 

If you're using the MediaListCollection query then I recommend sorting client side as thats probably going to be faster than waiting for the request cycle and you'll likely have some kind of client side sorting setup already. Though if you're using the paged media list query then thats not really an option sadly.

I'm going close this for now but after we open source we'll hopefully have have a few more eyes and more time to dedicate to the issue, so hopefully we'll be able to work something out then.
